# tracer/Makefile

NAME := tracer

OBJS := bam_$(NAME).o $(NAME).o \
		tracer_synchronize.o \
		tracer_evolve.o \
		tracer_interpolate.o \
		tracer_output.o \
		tracer_checkpoint.o

include $(TOP)/Makefile.subdirs
