# multigrid/Makefile

NAME := multigrid

OBJS := bam_$(NAME).o \
	exactsolve.o fasmg.o makestack.o multigrid.o \
	relax.o residual.o restrictprolong.o solve.o utility.o  print.o

include $(TOP)/Makefile.subdirs
