# bampi/Makefile

NAME := bampi

OBJS := bam_bampi.o bampi.o copy.o debug.o output.o openmp.o profile.o reduce.o split_box.o synchronize.o synchronize_fmr.o timer.o 

include $(TOP)/Makefile.subdirs

