# interpolate/Makefile

NAME := interpolate
OBJS := bam_$(NAME).o \
	barycentric.o \
	interpolate.o \
	interpolate_boxtobox_N.o \
	interpolate_global.o\
	lagrange.o\
	WENO.o\
	linear.o

include $(TOP)/Makefile.subdirs
