# Makefile

NAME := eos
OBJS := bam_$(NAME).o $(NAME).o \
	$(NAME)_analytic.o \
	$(NAME)_analytic_WT.o \
	$(NAME)_tab1D.o \
	$(NAME)_tab3D.o \
	$(NAME)_nuc.o \
	$(NAME)_tab1D_cold.o \
	$(NAME)_tab1D_hot.o \
	readers.o \
	steffen.o \
	NLS.o
	

include $(TOP)/Makefile.subdirs
