# matter/Makefile

NAME := matter
OBJS := bam_$(NAME).o $(NAME).o \
	hrsc.o \
	hrsc_numflx1d.o \
	hrsc_numflx1d_HLLD.o \
	hrsc_rec1d.o \
	matter_fluxes.o \
	matter_fluxes_grmhd.o \
    c_amr.o \
	hrsc_rec1d_PPM.o \

include $(TOP)/Makefile.subdirs


