name: bam-ci
channels:
  - local
  - conda-forge
  - https://enlil.gw.physik.uni-potsdam.de/~markin/mamba

dependencies:
  - gcc=13.1.0
  - binutils=2.40
  - git=2.41.0
  - go-task=3.28.0
  - gxx=13.1.0
  - make=4.3
  - mpi=1.0=openmpi
  - openmpi=4.1.5
  - openssl=3.1.2
  - pkg-config=0.29.2
  - boa=0.15.1
  - squashfuse=0.2.0
  - unzip=6.0
  - curl=8.2.1
  - scipy=1.11.2
  # - h5py