# output/Makefile

NAME := output

OBJS := bam_$(NAME).o $(NAME).o \
	output0d.o output1d.o output2d.o output3d.o \
        outputVTK.o \
		outputXDMF.o \
	outputShells.o \
	outputSphere.o

include $(TOP)/Makefile.subdirs
